name: geant4env
channels:
  - conda-forge
dependencies:
  - geant4
  - make
  - cmake
  - compilers
  - sed
  - mesa-libgl-devel-cos6-x86_64
  - mesa-dri-drivers-cos6-x86_64
  - libselinux-cos6-x86_64
  - libxdamage-cos6-x86_64
  - libxxf86vm-cos6-x86_64
  - python=3.9
  - boost=1.72.0
  - clhep=2.4.4.0
  - expat
  - freetype
  - libglu
  - qt=5.12
  - xerces-c
  - xorg-libx11
  - xorg-libxfixes
  - xorg-libxmu
  - zlib
  - xorg-libxfixes
  - libxext-cos6-x86_64
